import {
  Home,
  Utensils,
  Car,
  Zap,
  Film,
  Heart,
  GraduationCap,
  ShoppingBag,
  Plane,
  MoreHorizontal,
  Wallet,
  CreditCard,
  Laptop,
  Coffee,
  Gift,
  Pill,
  Dumbbell,
  Book,
  Briefcase,
  Bus,
  Train,
  Bike,
  Fuel,
  Wrench,
  Hammer,
  PaintBucket,
  Scissors,
  Shirt,
  DollarSign,
  TrendingUp,
  PiggyBank,
  Coins,
  Receipt,
  Tag,
  Phone,
  Tv,
  Gamepad2,
  Camera,
  Headphones,
  Watch,
  Pizza,
  Beer,
  Wine,
  IceCream,
  Cake,
  Apple,
  Carrot,
  Fish,
  Egg,
  Soup,
  Candy,
  Popcorn,
  Cookie,
  Donut,
  Croissant,
  CloudRain,
  Sun,
  Moon,
  Star,
  Sparkles,
  Trophy,
  Award,
  Medal,
} from 'lucide-react'

export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  home: Home,
  food: Utensils,
  car: Car,
  utility: Zap,
  entertainment: Film,
  health: Heart,
  education: GraduationCap,
  shopping: ShoppingBag,
  travel: Plane,
  other: MoreHorizontal,
  wallet: Wallet,
  credit: CreditCard,
  laptop: Laptop,
  coffee: Coffee,
  gift: Gift,
  pill: Pill,
  gym: Dumbbell,
  book: Book,
  briefcase: Briefcase,
  bus: Bus,
  train: Train,
  bike: Bike,
  fuel: Fuel,
  wrench: Wrench,
  hammer: Hammer,
  paint: PaintBucket,
  scissors: Scissors,
  shirt: Shirt,
  dollar: DollarSign,
  trending: TrendingUp,
  piggy: PiggyBank,
  coins: Coins,
  receipt: Receipt,
  tag: Tag,
  phone: Phone,
  tv: Tv,
  game: Gamepad2,
  camera: Camera,
  headphones: Headphones,
  watch: Watch,
  pizza: Pizza,
  beer: Beer,
  wine: Wine,
  icecream: IceCream,
  cake: Cake,
  apple: Apple,
  carrot: Carrot,
  fish: Fish,
  egg: Egg,
  soup: Soup,
  candy: Candy,
  popcorn: Popcorn,
  cookie: Cookie,
  donut: Donut,
  croissant: Croissant,
  rain: CloudRain,
  sun: Sun,
  moon: Moon,
  star: Star,
  sparkles: Sparkles,
  trophy: Trophy,
  award: Award,
  medal: Medal,
}

export function getTagIcon(iconName: string) {
  return iconMap[iconName] || Tag
}
