import {
  ShoppingBag,
  ShoppingCart,
  Utensils,
  Car,
  Home,
  Zap,
  Smartphone,
  Wifi,
  Gift,
  Coffee,
  PiggyBank,
  Briefcase,
  GraduationCap,
  Bus,
  Plane,
  Gamepad2,
  Music,
  Tv,
  Stethoscope,
  Ticket,
  Percent,
  TrendingUp,
  CreditCard,
  DollarSign,
  Landmark,
  Wallet,
  Receipt,
  Tag,
} from 'lucide-react'

export const categoryIcons = [
  { value: 'shopping-cart', label: 'Shopping Cart', icon: ShoppingCart },
  { value: 'shopping-bag', label: 'Shopping Bag', icon: ShoppingBag },
  { value: 'utensils', label: 'Food & Dining', icon: Utensils },
  { value: 'car', label: 'Transport', icon: Car },
  { value: 'bus', label: 'Bus', icon: Bus },
  { value: 'plane', label: 'Travel', icon: Plane },
  { value: 'home', label: 'Housing', icon: Home },
  { value: 'zap', label: 'Utilities', icon: Zap },
  { value: 'smartphone', label: 'Phone', icon: Smartphone },
  { value: 'wifi', label: 'Internet', icon: Wifi },
  { value: 'gift', label: 'Gifts', icon: Gift },
  { value: 'coffee', label: 'Coffee', icon: Coffee },
  { value: 'piggy-bank', label: 'Savings', icon: PiggyBank },
  { value: 'briefcase', label: 'Work', icon: Briefcase },
  { value: 'graduation-cap', label: 'Education', icon: GraduationCap },
  { value: 'gamepad-2', label: 'Entertainment', icon: Gamepad2 },
  { value: 'music', label: 'Music', icon: Music },
  { value: 'tv', label: 'Streaming', icon: Tv },
  { value: 'stethoscope', label: 'Health', icon: Stethoscope },
  { value: 'ticket', label: 'Events', icon: Ticket },
  { value: 'percent', label: 'Interest', icon: Percent },
  { value: 'trending-up', label: 'Investments', icon: TrendingUp },
  { value: 'credit-card', label: 'Credit Card', icon: CreditCard },
  { value: 'dollar-sign', label: 'Income', icon: DollarSign },
  { value: 'landmark', label: 'Bank', icon: Landmark },
  { value: 'wallet', label: 'Wallet', icon: Wallet },
  { value: 'receipt', label: 'Bills', icon: Receipt },
  { value: 'tag', label: 'Other', icon: Tag },
]

export const getCategoryIcon = (value: string | undefined | null) => {
  if (!value) return Tag
  const found = categoryIcons.find((icon) => icon.value === value)
  return found ? found.icon : Tag
}
