/** Generated by generate:translations. Do not edit. 
Regenerate with `pnpm run generate:translations`. */
import { en } from './en'
import { de } from './de'

export { en }
export { de }

export const translations = {
  en,
  de,
}
